apiVersion: v1
kind: Service
metadata:
  name: speech-tts-nemo-service
  namespace: sarvam
  labels:
    app: speech-tts-nemo
spec:
  selector:
    app: speech-tts-nemo
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: model-port
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics-port
