apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-client-rolebinding
  namespace: sarvam
subjects:
- kind: User
  name: my-client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-client-role
  apiGroup: rbac.authorization.k8s.io
